/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clients;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 *  
 */
public class RetrieveAccount extends javax.swing.JFrame {

    private Helper helper;
    private ProgressTask progressTask;
    private boolean waiting = false;

    /**
     * Creates new form ForgotAccount
     */
    public RetrieveAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        retrieveButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Account");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        emailLabel.setText("Email :");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(210, 84, 76, 26);
        getContentPane().add(emailText);
        emailText.setBounds(210, 128, 97, 28);

        retrieveButton.setText("Retrieve");
        retrieveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                retrieveButtonMouseReleased(evt);
            }
        });
        getContentPane().add(retrieveButton);
        retrieveButton.setBounds(220, 219, 100, 23);

        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backLabelMouseReleased(evt);
            }
        });
        getContentPane().add(backLabel);
        backLabel.setBounds(60, 40, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        getContentPane().setBackground(Color.GRAY);
        helper = new Helper();

        //size and location of window opened
        setSize(width * 40 / 100, height * 36 / 100);
        setLocationRelativeTo(null);

        //initialize components
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/img/back.png"));
        Image image = imageIcon.getImage();
        Image newimg = image.getScaledInstance(width * 3 / 100, height * 2 / 100, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);

        backLabel.setSize(width * 3 / 100, height * 2 / 100);
        backLabel.setLocation(width * 2 / 100, height * 2 / 100);
        backLabel.setIcon(imageIcon);

        Font currentFont = emailLabel.getFont();
        emailLabel.setSize(width * 10 / 100, height * 5 / 100);
        emailLabel.setLocation(width * 10 / 100, height * 8 / 100);
        emailLabel.setFont(currentFont.deriveFont(Font.BOLD, width * 1.1f / 100));
        emailText.setSize(width * 10 / 100, height * 4 / 100);
        emailText.setLocation(width * 15 / 100, height * 9 / 100);

        retrieveButton.setSize(width * 8 / 100, height * 5 / 100);
        retrieveButton.setLocation(width * 16 / 100, height * 18 / 100);
        retrieveButton.setFont(currentFont.deriveFont(Font.PLAIN, width * 0.8f / 100));
    }//GEN-LAST:event_formWindowOpened

    private void retrieveButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrieveButtonMouseReleased
        if (retrieveButton.isEnabled()) {
            if (!helper.isConnected()) {
                JOptionPane.showMessageDialog(this,
                        "Please check your internet connection!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                if (helper.emailValidity(emailText.getText().trim())) {
                    progressTask = new RetrieveAccount.ProgressTask();
                    progressTask.execute();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Please enter a valid Email!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_retrieveButtonMouseReleased

    private void backLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseReleased
        if (!waiting) {
            new Main().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_backLabelMouseReleased

    class ProgressTask extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() throws ClassNotFoundException, SQLException, IOException, MessagingException {
            setCursor(Cursor.WAIT_CURSOR);
            waiting = true;
            retrieveButton.setEnabled(false);
            emailText.setEnabled(false);
            String urlString = helper.getDomainName() + "checkClientsByEmail.php?email=" + emailText.getText().trim();
            String result = helper.getMethod(urlString);
            if (result.trim().length() == 0) {
                JOptionPane.showMessageDialog(getContentPane(),
                        "The email doesn't exist!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                String[] parts = result.split("\\$");
                String text = "Dear Sir,<br><br>Username : " + parts[0] + "<br><br>Password : " + parts[1];
                helper.sendEmail(emailText.getText().trim(), text, "PEC - Retrieve Account");
                JOptionPane.showMessageDialog(getContentPane(),
                        "An email has been sent to your mail!");
            }
            waiting = false;
            retrieveButton.setEnabled(true);
            emailText.setEnabled(true);
            setCursor(Cursor.DEFAULT_CURSOR);
            return null;
        }

        /*
     * Executed in event dispatching thread
         */
        @Override
        public void done() {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetrieveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetrieveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetrieveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetrieveAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetrieveAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton retrieveButton;
    // End of variables declaration//GEN-END:variables
}
